### ISSUE TITLE
How to avoid inf value while feature extracting in Matlab?

### ISSUE THREAD

**Issue by jemappelleMarie** [the-deep-learners/TensorFlow-LiveLessons#25] opened 2019-05-16 13:41 UTC
I’m trying to extract features from some EEG signals. One of the trails in my for loop creates inf value and emd doesn’t accept it so it causes an error! Would you please tell me how I can fix it?!
Thanks a lot in advance.
My code:

fs = 250;

idSubject = 1:9;
idTraining = 1:3;

for ii = idSubject
    disp(ii)
    for jj = idTraining
        disp(jj)
        [signal,H] = sload(['B0' num2str(ii) '0' num2str(jj) 'T.gdf']);
        
        s = 1;
        for ch = 1:3
            Signal(:,s) = signal(:,ch);
            s = s + 1;
        end

        Signal = Signal';
        SignalMean = nanmean(Signal);
        SignalMean = SignalMean';

        LabelLeft = find(H.Classlabel == 1);  %Signal of left hand
        LabelLeft = LabelLeft';
        LabelRight = find(H.Classlabel == 2); %Signal of right hand
        LabelRight = LabelRight';

        s = 1;
        for i = LabelLeft
            SignalL = SignalMean(H.TRIG(i)+fs:H.TRIG(i)+(3*fs)-1,1);
            SignalLeft{s,:} = emd(SignalL,'MAXMODES',4);
            s = s+1;

            clear SignalL
        end
        SignalLeft = cell2mat(SignalLeft);
        sLeftall{jj,:} = SignalLeft;

        s = 1;
        for i = LabelRight
            SignalR = SignalMean(H.TRIG(i)+fs:H.TRIG(i)+(3*fs)-1,1);
            SignalRight{s,:} = emd(SignalR,'MAXMODES',4);
            s = s+1;

            clear SignalR
        end
        SignalRight = cell2mat(SignalRight);
        sRightall{jj,:} = SignalRight;
        
        clear SignalLeft SignalRight signal Signal SignalMean H LabelLeft LabelRight      
    end
    sLeftall = cell2mat(sLeftall);
    sRightall = cell2mat(sRightall);
    
    signalLeftAll{ii,:} = sLeftall;
    signalRightAll{ii,:} = sLeftall;
    
    clear sLeftall sRightall
end

**Comment by jonkrohn** [comment] 2019-05-16 13:45
Hi @jemappelleMarie -- I don't see how this EEG-specific Matlab code is in any way related to my Python code for deep learning. 

This is not a bug in this code repo. I'm closing the issue.

**Closed by jonkrohn** 2019-05-16 13:45 UTC

**Comment by jonkrohn** [comment] 2019-05-16 13:51
Perhaps try StackOverflow?

**Comment by jemappelleMarie** [comment] 2019-05-16 13:53
Hi
Oops, I'm so sorry, my bad! I didn't want to create the issue here!  I made a stupid mistake.
So sorry for that :(
Yeah, I did.
 Thanks a lot


    On Thursday, May 16, 2019, 6:21:57 PM GMT+4:30, Jon Krohn <notifications@github.com> wrote:  
 
 
Perhaps try StackOverflow?

**Comment by jonkrohn** [comment] 2019-05-16 13:55
haha no problem 😄
